"""testing batch

Revision ID: 16f1b762ea0a
Revises: 8d40d1c7fbc7
Create Date: 2022-03-14 18:31:38.865034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f1b762ea0a'
down_revision = '8d40d1c7fbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
