"""foreign key 'on delete'

Revision ID: 39cd3f1c4958
Revises: 9c174a97d76b
Create Date: 2022-03-17 10:19:59.001211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cd3f1c4958'
down_revision = '9c174a97d76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cars_races_id_race', type_='foreignkey')
        batch_op.create_foreign_key('fk_cars_races_id_race', 'races', ['race'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_heat_runs_lanes_id_lane', type_='foreignkey')
        batch_op.drop_constraint('fk_heat_runs_cars_id_car', type_='foreignkey')
        batch_op.drop_constraint('fk_heat_runs_heats_id_heat', type_='foreignkey')
        batch_op.create_foreign_key('fk_heat_runs_heats_id_heat', 'heats', ['heat'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_heat_runs_lanes_id_lane', 'lanes', ['lane'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_heat_runs_cars_id_car', 'cars', ['car'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('heats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_heats_races_id_race', type_='foreignkey')
        batch_op.create_foreign_key('fk_heats_races_id_race', 'races', ['race'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lanes_tracks_id_track', type_='foreignkey')
        batch_op.create_foreign_key('fk_lanes_tracks_id_track', 'tracks', ['track'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_constraint('fk_races_tracks_id_track', type_='foreignkey')
        batch_op.drop_constraint('fk_races_users_id_owner', type_='foreignkey')
        batch_op.create_foreign_key('fk_races_users_id_owner', 'users', ['owner'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_races_tracks_id_track', 'tracks', ['track'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_constraint('fk_races_tracks_id_track', type_='foreignkey')
        batch_op.drop_constraint('fk_races_users_id_owner', type_='foreignkey')
        batch_op.create_foreign_key('fk_races_users_id_owner', 'users', ['owner'], ['id'])
        batch_op.create_foreign_key('fk_races_tracks_id_track', 'tracks', ['track'], ['id'])

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lanes_tracks_id_track', type_='foreignkey')
        batch_op.create_foreign_key('fk_lanes_tracks_id_track', 'tracks', ['track'], ['id'])

    with op.batch_alter_table('heats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_heats_races_id_race', type_='foreignkey')
        batch_op.create_foreign_key('fk_heats_races_id_race', 'races', ['race'], ['id'])

    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_heat_runs_cars_id_car', type_='foreignkey')
        batch_op.drop_constraint('fk_heat_runs_lanes_id_lane', type_='foreignkey')
        batch_op.drop_constraint('fk_heat_runs_heats_id_heat', type_='foreignkey')
        batch_op.create_foreign_key('fk_heat_runs_heats_id_heat', 'heats', ['heat'], ['id'])
        batch_op.create_foreign_key('fk_heat_runs_cars_id_car', 'cars', ['car'], ['id'])
        batch_op.create_foreign_key('fk_heat_runs_lanes_id_lane', 'lanes', ['lane'], ['id'])

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cars_races_id_race', type_='foreignkey')
        batch_op.create_foreign_key('fk_cars_races_id_race', 'races', ['race'], ['id'])

    # ### end Alembic commands ###
