"""Skip reverse relation lane -> heat_runs

Revision ID: 3efb56e0d6ee
Revises: b0faa119ff04
Create Date: 2022-03-12 10:34:48.690913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efb56e0d6ee'
down_revision = 'b0faa119ff04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
