"""Adding list of lanes to track

Revision ID: 41de48cd0dfe
Revises: 52c26fe8137b
Create Date: 2022-03-12 12:08:30.346382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41de48cd0dfe'
down_revision = '52c26fe8137b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
