"""Skip reverse relation lane -> heat_runs

Revision ID: 463ef89b122c
Revises: 3efb56e0d6ee
Create Date: 2022-03-12 10:38:46.342809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463ef89b122c'
down_revision = '3efb56e0d6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
