"""Adding list of lanes to track

Revision ID: 52c26fe8137b
Revises: c4b580360c54
Create Date: 2022-03-12 12:03:16.011078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c26fe8137b'
down_revision = 'c4b580360c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
