"""HeatRun.delta_ms defaults to NULL

Revision ID: 8a080899e190
Revises: 39cd3f1c4958
Create Date: 2022-03-17 14:01:13.565892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a080899e190'
down_revision = '39cd3f1c4958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
