"""PostgreSQL DB

Revision ID: 8d40d1c7fbc7
Revises: fac9d2c9c57a
Create Date: 2022-03-14 17:23:27.243085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d40d1c7fbc7'
down_revision = 'fac9d2c9c57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
