"""Modifying CreateUser

Revision ID: 94da72529e43
Revises: 463ef89b122c
Create Date: 2022-03-12 11:02:10.143347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94da72529e43'
down_revision = '463ef89b122c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
