"""fastapi-users data schema

Revision ID: 9c174a97d76b
Revises: 
Create Date: 2022-03-17 00:03:18.515912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c174a97d76b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('lanes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('lane_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track'], ['tracks.id'], name='fk_lanes_tracks_id_track'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track', 'lane_number', name='uc_lanes_track_lane_number')
    )
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lanes_lane_number'), ['lane_number'], unique=False)

    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('watch_link', sa.String(length=25), nullable=False),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('owner', sa.CHAR(36), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_races_users_id_owner'),
    sa.ForeignKeyConstraint(['track'], ['tracks.id'], name='fk_races_tracks_id_track'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_races_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_watch_link'), ['watch_link'], unique=True)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['race'], ['races.id'], name='fk_cars_races_id_race'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race', 'car_number', name='uc_cars_race_car_number')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cars_car_number'), ['car_number'], unique=False)

    op.create_table('heats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('race', sa.Integer(), nullable=True),
    sa.Column('heat_number', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race'], ['races.id'], name='fk_heats_races_id_race'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race', 'heat_number', name='uc_heats_race_heat_number')
    )
    with op.batch_alter_table('heats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heats_heat_number'), ['heat_number'], unique=False)

    op.create_table('heat_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Integer(), nullable=True),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('delta_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car'], ['cars.id'], name='fk_heat_runs_cars_id_car'),
    sa.ForeignKeyConstraint(['heat'], ['heats.id'], name='fk_heat_runs_heats_id_heat'),
    sa.ForeignKeyConstraint(['lane'], ['lanes.id'], name='fk_heat_runs_lanes_id_lane'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heat_runs')
    with op.batch_alter_table('heats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heats_heat_number'))

    op.drop_table('heats')
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cars_car_number'))

    op.drop_table('cars')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_watch_link'))
        batch_op.drop_index(batch_op.f('ix_races_race_date'))
        batch_op.drop_index(batch_op.f('ix_races_name'))

    op.drop_table('races')
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lanes_lane_number'))

    op.drop_table('lanes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tracks')
    # ### end Alembic commands ###
