"""Testing

Revision ID: ab93bd7e33bf
Revises: 41de48cd0dfe
Create Date: 2022-03-14 16:23:06.263717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab93bd7e33bf'
down_revision = '41de48cd0dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
