"""PostgreSQL DB

Revision ID: fac9d2c9c57a
Revises: ab93bd7e33bf
Create Date: 2022-03-14 16:25:46.697301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac9d2c9c57a'
down_revision = 'ab93bd7e33bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
