"""Add heat_car_lanes table

Revision ID: fbe7cdc475d8
Revises: 13520ec4d218
Create Date: 2022-03-11 20:56:58.648504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe7cdc475d8'
down_revision = '13520ec4d218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heat_car_lanes',
    sa.Column('race', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Integer(), nullable=True),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car'], ['cars.id'], name='fk_heat_car_lanes_cars_id_car'),
    sa.ForeignKeyConstraint(['heat'], ['heats.id'], name='fk_heat_car_lanes_heats_id_heat'),
    sa.ForeignKeyConstraint(['lane'], ['lanes.id'], name='fk_heat_car_lanes_lanes_id_lane'),
    sa.ForeignKeyConstraint(['race'], ['races.id'], name='fk_heat_car_lanes_races_id_race'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race', 'number', name='uc_heat_car_lanes_race_number')
    )
    with op.batch_alter_table('heat_car_lanes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heat_car_lanes_number'), ['number'], unique=False)

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_link', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=6), nullable=False))
        batch_op.create_index(batch_op.f('ix_races_watch_link'), ['watch_link'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_complete')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sec', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('heat_car_lane', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uc_runs_heat_car', type_='unique')
        batch_op.drop_constraint('uc_runs_heat_lane', type_='unique')
        batch_op.create_unique_constraint('uc_runs_heat_car_lane', ['heat_car_lane'])
        batch_op.drop_constraint('fk_runs_cars_id_car', type_='foreignkey')
        batch_op.drop_constraint('fk_runs_lanes_id_lane', type_='foreignkey')
        batch_op.drop_constraint('fk_runs_heats_id_heat', type_='foreignkey')
        batch_op.create_foreign_key('fk_runs_heat_car_lanes_id_heat_car_lane', 'heat_car_lanes', ['heat_car_lane'], ['id'])
        batch_op.drop_column('heat')
        batch_op.drop_column('mps')
        batch_op.drop_column('fps')
        batch_op.drop_column('lane')
        batch_op.drop_column('car')
        batch_op.drop_column('mph')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=False))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mph', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('car', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lane', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fps', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('mps', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('heat', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_runs_heat_car_lanes_id_heat_car_lane', type_='foreignkey')
        batch_op.create_foreign_key('fk_runs_heats_id_heat', 'heats', ['heat'], ['id'])
        batch_op.create_foreign_key('fk_runs_lanes_id_lane', 'lanes', ['lane'], ['id'])
        batch_op.create_foreign_key('fk_runs_cars_id_car', 'cars', ['car'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('uc_runs_heat_lane', ['heat', 'lane'])
        batch_op.create_unique_constraint('uc_runs_heat_car', ['heat', 'car'])
        batch_op.drop_column('heat_car_lane')
        batch_op.drop_column('sec')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_races_watch_link'))
        batch_op.drop_column('status')
        batch_op.drop_column('watch_link')

    with op.batch_alter_table('heat_car_lanes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heat_car_lanes_number'))

    op.drop_table('heat_car_lanes')
    # ### end Alembic commands ###
