"""HeatRun.delta_ms defaults to NULL

Revision ID: fe6b694c788c
Revises: 8a080899e190
Create Date: 2022-03-17 15:26:48.619484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6b694c788c'
down_revision = '8a080899e190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.alter_column('delta_ms',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.alter_column('delta_ms',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
