"""HeatRun unique constraints on car and lane per heat

Revision ID: 4fc2caa73f3b
Revises: b47b3018b041
Create Date: 2022-03-17 17:06:52.218868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc2caa73f3b'
down_revision = 'b47b3018b041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uc_heat_runs_heat_car', ['heat', 'car'])
        batch_op.create_unique_constraint('uc_heat_runs_heat_lane', ['heat', 'lane'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.drop_constraint('uc_heat_runs_heat_lane', type_='unique')
        batch_op.drop_constraint('uc_heat_runs_heat_car', type_='unique')

    # ### end Alembic commands ###
