"""HeatRun.delta_ms defaults to NULL

Revision ID: 93a1888eedb5
Revises: b9e9db20e75a
Create Date: 2022-03-17 14:01:19.352000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a1888eedb5'
down_revision = 'b9e9db20e75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
