"""HeatRun.delta_ms defaults to NULL

Revision ID: b47b3018b041
Revises: 93a1888eedb5
Create Date: 2022-03-17 15:26:54.974953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47b3018b041'
down_revision = '93a1888eedb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.alter_column('delta_ms',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heat_runs', schema=None) as batch_op:
        batch_op.alter_column('delta_ms',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
