"""Edit races.place max_length

Revision ID: 13520ec4d218
Revises: 9234e34c6309
Create Date: 2022-03-05 22:08:05.941207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13520ec4d218'
down_revision = '9234e34c6309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
