"""Reworking data model

Revision ID: 2aa98fe65fc3
Revises: fbe7cdc475d8
Create Date: 2022-03-12 10:17:26.836487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa98fe65fc3'
down_revision = 'fbe7cdc475d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('heat_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Integer(), nullable=True),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('delta_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car'], ['cars.id'], name='fk_heat_runs_cars_id_car'),
    sa.ForeignKeyConstraint(['heat'], ['heats.id'], name='fk_heat_runs_heats_id_heat'),
    sa.ForeignKeyConstraint(['lane'], ['lanes.id'], name='fk_heat_runs_lanes_id_lane'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_races')
    op.drop_table('runs')
    with op.batch_alter_table('heat_car_lanes', schema=None) as batch_op:
        batch_op.drop_index('ix_heat_car_lanes_number')

    op.drop_table('heat_car_lanes')
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_number', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_cars_number')
        batch_op.drop_constraint('uc_cars_race_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_cars_car_number'), ['car_number'], unique=False)
        batch_op.create_unique_constraint('uc_cars_race_car_number', ['race', 'car_number'])
        batch_op.drop_column('number')

    with op.batch_alter_table('heats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heat_number', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_heats_number')
        batch_op.drop_constraint('uc_heats_race_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_heats_heat_number'), ['heat_number'], unique=False)
        batch_op.create_unique_constraint('uc_heats_race_heat_number', ['race', 'heat_number'])
        batch_op.drop_column('number')

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lane_number', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_lanes_number')
        batch_op.drop_constraint('uc_lanes_race_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_lanes_lane_number'), ['lane_number'], unique=False)
        batch_op.create_unique_constraint('uc_lanes_track_lane_number', ['track', 'lane_number'])
        batch_op.drop_constraint('fk_lanes_races_id_race', type_='foreignkey')
        batch_op.create_foreign_key('fk_lanes_races_id_track', 'races', ['track'], ['id'])
        batch_op.drop_column('race')
        batch_op.drop_column('number')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_link', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('track', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=6), nullable=False))
        batch_op.create_index(batch_op.f('ix_races_watch_link'), ['watch_link'], unique=True)
        batch_op.create_foreign_key('fk_races_tracks_id_track', 'tracks', ['track'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_races_tracks_id_track', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_races_watch_link'))
        batch_op.drop_column('status')
        batch_op.drop_column('track')
        batch_op.drop_column('watch_link')

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('race', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_lanes_races_id_track', type_='foreignkey')
        batch_op.create_foreign_key('fk_lanes_races_id_race', 'races', ['race'], ['id'])
        batch_op.drop_constraint('uc_lanes_track_lane_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_lanes_lane_number'))
        batch_op.create_unique_constraint('uc_lanes_race_number', ['race', 'number'])
        batch_op.create_index('ix_lanes_number', ['number'], unique=False)
        batch_op.drop_column('lane_number')
        batch_op.drop_column('track')

    with op.batch_alter_table('heats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('uc_heats_race_heat_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_heats_heat_number'))
        batch_op.create_unique_constraint('uc_heats_race_number', ['race', 'number'])
        batch_op.create_index('ix_heats_number', ['number'], unique=False)
        batch_op.drop_column('heat_number')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('uc_cars_race_car_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_cars_car_number'))
        batch_op.create_unique_constraint('uc_cars_race_number', ['race', 'number'])
        batch_op.create_index('ix_cars_number', ['number'], unique=False)
        batch_op.drop_column('car_number')

    op.create_table('heat_car_lanes',
    sa.Column('race', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('heat', sa.INTEGER(), nullable=True),
    sa.Column('car', sa.INTEGER(), nullable=True),
    sa.Column('lane', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['car'], ['cars.id'], name='fk_heat_car_lanes_cars_id_car'),
    sa.ForeignKeyConstraint(['heat'], ['heats.id'], name='fk_heat_car_lanes_heats_id_heat'),
    sa.ForeignKeyConstraint(['lane'], ['lanes.id'], name='fk_heat_car_lanes_lanes_id_lane'),
    sa.ForeignKeyConstraint(['race'], ['races.id'], name='fk_heat_car_lanes_races_id_race'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race', 'number', name='uc_heat_car_lanes_race_number')
    )
    with op.batch_alter_table('heat_car_lanes', schema=None) as batch_op:
        batch_op.create_index('ix_heat_car_lanes_number', ['number'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('race', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['race'], ['races.id'], name='fk_runs_races_id_race'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_races',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('place', sa.VARCHAR(length=256), nullable=True),
    sa.Column('race_date', sa.DATE(), nullable=True),
    sa.Column('race_time', sa.TIME(), nullable=True),
    sa.Column('owner', sa.INTEGER(), nullable=True),
    sa.Column('watch_link', sa.VARCHAR(length=25), nullable=False),
    sa.Column('status', sa.VARCHAR(length=6), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_races_users_id_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('heat_runs')
    op.drop_table('tracks')
    # ### end Alembic commands ###
