"""Modifying CreateUser

Revision ID: 412486613483
Revises: ac4649a5ae7b
Create Date: 2022-03-12 11:41:04.297173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412486613483'
down_revision = 'ac4649a5ae7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
