"""Skip reverse relation track -> races

Revision ID: 4c1f19dbfe90
Revises: 2aa98fe65fc3
Create Date: 2022-03-12 10:23:44.910172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1f19dbfe90'
down_revision = '2aa98fe65fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
