"""Modifying CreateUser

Revision ID: ac4649a5ae7b
Revises: a262869b8409
Create Date: 2022-03-12 11:31:42.888052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4649a5ae7b'
down_revision = 'a262869b8409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
