"""Tie lane to track, not race

Revision ID: b0faa119ff04
Revises: 4c1f19dbfe90
Create Date: 2022-03-12 10:24:46.301908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0faa119ff04'
down_revision = '4c1f19dbfe90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lanes_races_id_track', type_='foreignkey')
        batch_op.create_foreign_key('fk_lanes_tracks_id_track', 'tracks', ['track'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lanes_tracks_id_track', type_='foreignkey')
        batch_op.create_foreign_key('fk_lanes_races_id_track', 'races', ['track'], ['id'])

    # ### end Alembic commands ###
