"""Adding list of lanes to track

Revision ID: c4b580360c54
Revises: 412486613483
Create Date: 2022-03-12 12:01:10.779270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b580360c54'
down_revision = '412486613483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
